# Vehicle Counter configuration.

DEFAULT_CONFIDENCE_THRESHOLD = 0.30
DEFAULT_FRAME_SKIP = 1
MODEL_SIZE_OPTIONS = ("nano", "small", "medium")
DEFAULT_ENABLED_CLASSES = ("car", "motorcycle", "bus", "truck", "bicycle")
PRESET_CUSTOM = "custom"
PRESET_LIVE_LOW_LATENCY = "live_low_latency"
PRESET_BALANCED_COUNTING = "balanced_counting"
PRESET_MOTORCYCLE_FOCUS = "motorcycle_focus"
DEFAULT_PRESET = PRESET_BALANCED_COUNTING
DEFAULT_MODEL_SIZE = "small"

# UI settings
WINDOW_TITLE = "Vehicle Counter"
WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 940
WINDOW_MIN_WIDTH = 1280
WINDOW_MIN_HEIGHT = 760
RIGHT_PANEL_MIN_WIDTH = 420
LEFT_PANEL_MIN_WIDTH = 700
INITIAL_SPLITTER_LEFT_RATIO = 0.7
